name: Bisect on comment

on: pull_request

jobs:
  bisect:
    # This job only runs for issue comments
    name: Execute trusted code
    #if: github.actor == 'LilithHafner' && contains(github.event.comment.body, '`bisect()`')
    runs-on: ubuntu-latest
    # This elevates the permissions of secrets.GITHUB_TOKEN. Only the 
    # final step has that token and can use those permissions and the 
    # permissions should be limited to working with issues and pull 
    # requests and such. Still, this is vulnerable to arbitrary remote
    # code execution (e.g. deleting all issues and pull requests) by 
    # authorized actors. Be careful which actors you authorize.
    permissions:
      issues: write
      pull-requests: write
    steps:
      #- uses: actions/checkout@v4
      #  with:
      #    fetch-depth: 0
      #- uses: julia-actions/setup-julia@v1
      #- uses: julia-actions/cache@v1
      #- uses: julia-actions/julia-buildpkg@v1  
      #- name: Write to file
      #  run: echo $BODY > BISECTION_FILE_LAMJGUDOQZGFSDQBKQUN
      #  env:
      #    BODY: ${{ github.event.comment.body }}
      #- name: Run bisection
      #  run: julia --project -e 'using Bisect; Bisect.workflow("BISECTION_FILE_LAMJGUDOQZGFSDQBKQUN")'
      #- name: Add comment
      #  run: gh issue comment "$NUMBER" --body-file BISECTION_FILE_LAMJGUDOQZGFSDQBKQUN
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    GH_REPO: ${{ github.repository }}
      #    NUMBER: ${{ github.event.issue.number }}
      - name: check commenter permissions
        run: >-
          PERMISSION=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/LilithHafner/Bisect.jl/collaborators/LilithHafner/permission | jq .permission);
          [ $PERMISSION = "\"write\"" ] || [ $PERMISSION = "\"admin\"" ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
