# This is a bisect workflow that is manually triggered

name: Bisect

# Controls when the action will run. Workflow runs when invoked in an issue (incl. PR) comment
on:
  issue_comment:                                     
    types: [created] # Edits do not trigger or re-trigger. Must post a new comment.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "bisect"
  bisect:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Print actor
      run: echo ${{ github.actor }}
